### ISSUE TITLE
[-] Device Vendor ID: Unspecified, Product ID: Unspecified Pingcode: Unspecified not found!

### ISSUE THREAD

**Issue by F-tthj** [Megant88/Valorant-GUI-Cheat-Arduino#14]
how do i solve  this problem after following the installing procedures?
[-] Device Vendor ID: Unspecified, Product ID: Unspecified Pingcode: Unspecified not found!
some1 pls help

**Comment by Megant88** [comment]
its totally outdated, dont even try to use this lol, this is not useful for you, however you fix this by uploading the arduino scetch to the arduino
