### ISSUE TITLE
using without gui

### ISSUE THREAD

**Issue by nanoeray** [Megant88/Valorant-GUI-Cheat-Arduino#2]
can we use it without gui, only with running arduino?

**Comment by Megant88** [comment]
Yes, very use, remove the GUI calls, or completely delete the GUI and just run the code which calls the cheese.py

**Comment by xerinha** [comment]
Is using without the gui safe?

**Comment by Megant88** [comment]
yes it is

**Comment by xerinha** [comment]
como faz pra usar sem GUI ?
